### ISSUE TITLE
Additional files missing

### ISSUE THREAD

**Issue by mindrunner** [mortie/dots#1]
`sway/lock.sh` references `glitch.c` and `lock.svg`. However, they seem nowhere in this repo? Any chance you share them as well?

**Comment by mortie** [comment]
Hey, it has been a couple of years, sorry about that :sweat_smile: anyway, all referenced files are here now (though mostly because I re-did my sway config and don't have lock.svg and glitch.c any more. I'm pretty sure I've lost those files for good at this point)
